name: multi_image_tracker
description: A flutter package which makes it easy to track a series of images.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: